/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_util_callback_OSVR_PoseCallback */

#ifndef _Included_osvr_util_callback_OSVR_PoseCallback
#define _Included_osvr_util_callback_OSVR_PoseCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_util_callback_OSVR_PoseCallback
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_util_callback_OSVR_1PoseCallback_initializeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
