/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_util_OSVR_RadialDistortionParameters */

#ifndef _Included_osvr_util_OSVR_RadialDistortionParameters
#define _Included_osvr_util_OSVR_RadialDistortionParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_util_OSVR_RadialDistortionParameters
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_util_OSVR_1RadialDistortionParameters_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_util_OSVR_RadialDistortionParameters
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_util_OSVR_1RadialDistortionParameters_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
