/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_java_examples_clients_MinimalInit */

#ifndef _Included_osvr_java_examples_clients_MinimalInit
#define _Included_osvr_java_examples_clients_MinimalInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_java_examples_clients_MinimalInit
 * Method:    main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_osvr_java_examples_clients_MinimalInit_main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
