/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_clientkit_OSVR_DisplayConfig */

#ifndef _Included_osvr_clientkit_OSVR_DisplayConfig
#define _Included_osvr_clientkit_OSVR_DisplayConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    valid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_valid
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    checkStartup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_checkStartup
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    getNumDisplayInputs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_getNumDisplayInputs
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    getNumViewers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_getNumViewers
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    getViewer
 * Signature: (ILosvr/clientkit/OSVR_Viewer;)Losvr/clientkit/OSVR_Viewer;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_getViewer
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    getEye
 * Signature: (JILosvr/clientkit/OSVR_Eye;)Losvr/clientkit/OSVR_Eye;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_getEye
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    getSurface
 * Signature: (IIILosvr/clientkit/OSVR_Surface;)Losvr/clientkit/OSVR_Surface;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_getSurface
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    initializeNative
 * Signature: (Losvr/clientkit/ContextWrapper;)V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_initializeNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     osvr_clientkit_OSVR_DisplayConfig
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1DisplayConfig_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
