/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_clientkit_InterfaceState */

#ifndef _Included_osvr_clientkit_InterfaceState
#define _Included_osvr_clientkit_InterfaceState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_clientkit_InterfaceState
 * Method:    osvrGetPoseState
 * Signature: (JLosvr/clientkit/Interface;Losvr/util/OSVR_TimeValue;Losvr/util/OSVR_Pose3;)I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_InterfaceState_osvrGetPoseState
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     osvr_clientkit_InterfaceState
 * Method:    osvrGetPositionState
 * Signature: (JLosvr/clientkit/Interface;Losvr/util/OSVR_TimeValue;Losvr/util/OSVR_Vec3;)I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_InterfaceState_osvrGetPositionState
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     osvr_clientkit_InterfaceState
 * Method:    osvrGetOrientationState
 * Signature: (JLosvr/clientkit/Interface;Losvr/util/OSVR_TimeValue;Losvr/util/OSVR_Quaternion;)I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_InterfaceState_osvrGetOrientationState
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     osvr_clientkit_InterfaceState
 * Method:    osvrGetButtonState
 * Signature: (JLosvr/clientkit/Interface;Losvr/util/OSVR_TimeValue;Losvr/util/OSVR_Button;)I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_InterfaceState_osvrGetButtonState
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class:     osvr_clientkit_InterfaceState
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_InterfaceState_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_InterfaceState
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_InterfaceState_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
