/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_clientkit_DisplayHelper */

#ifndef _Included_osvr_clientkit_DisplayHelper
#define _Included_osvr_clientkit_DisplayHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_clientkit_DisplayHelper
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_DisplayHelper_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_DisplayHelper
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_DisplayHelper_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_DisplayHelper
 * Method:    getViewMatrix
 * Signature: (JJI[F)Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_DisplayHelper_getViewMatrix
  (JNIEnv *, jobject, jlong, jlong, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
