/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_clientkit_OSVR_Eye */

#ifndef _Included_osvr_clientkit_OSVR_Eye
#define _Included_osvr_clientkit_OSVR_Eye
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_clientkit_OSVR_Eye
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1Eye_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Eye
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1Eye_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Eye
 * Method:    getNumSurfaces
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_OSVR_1Eye_getNumSurfaces
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Eye
 * Method:    getSurface
 * Signature: (ILosvr/clientkit/OSVR_Surface;)Losvr/clientkit/OSVR_Surface;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1Eye_getSurface
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Eye
 * Method:    getPose
 * Signature: (Losvr/util/OSVR_Pose3;)Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_OSVR_1Eye_getPose
  (JNIEnv *, jobject, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Eye
 * Method:    getViewMatrix
 * Signature: (I[F)Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_OSVR_1Eye_getViewMatrix
  (JNIEnv *, jobject, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
