/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_util_OSVR_Vec3 */

#ifndef _Included_osvr_util_OSVR_Vec3
#define _Included_osvr_util_OSVR_Vec3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_util_OSVR_Vec3
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_util_OSVR_1Vec3_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_util_OSVR_Vec3
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_util_OSVR_1Vec3_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
