/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_util_callback_OSVR_Callback_CallbackType */

#ifndef _Included_osvr_util_callback_OSVR_Callback_CallbackType
#define _Included_osvr_util_callback_OSVR_Callback_CallbackType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
