/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_clientkit_OSVR_Surface */

#ifndef _Included_osvr_clientkit_OSVR_Surface
#define _Included_osvr_clientkit_OSVR_Surface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_clientkit_OSVR_Surface
 * Method:    getRelativeViewport
 * Signature: ()Losvr/clientkit/RelativeViewport;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1Surface_getRelativeViewport
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Surface
 * Method:    getProjectionMatrix
 * Signature: (FFI[[F)V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1Surface_getProjectionMatrix
  (JNIEnv *, jobject, jfloat, jfloat, jint, jobjectArray);

/*
 * Class:     osvr_clientkit_OSVR_Surface
 * Method:    isDistortionRequested
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_OSVR_1Surface_isDistortionRequested
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Surface
 * Method:    getRadialDistortion
 * Signature: ()Losvr/util/OSVR_RadialDistortionParameters;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1Surface_getRadialDistortion
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Surface
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1Surface_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Surface
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1Surface_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
