/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_clientkit_ContextWrapper */

#ifndef _Included_osvr_clientkit_ContextWrapper
#define _Included_osvr_clientkit_ContextWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_clientkit_ContextWrapper
 * Method:    initializeNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_osvr_clientkit_ContextWrapper_initializeNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     osvr_clientkit_ContextWrapper
 * Method:    updateNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_ContextWrapper_updateNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_ContextWrapper
 * Method:    getStringParameter
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_osvr_clientkit_ContextWrapper_getStringParameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     osvr_clientkit_ContextWrapper
 * Method:    checkStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_ContextWrapper_checkStatus
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_ContextWrapper
 * Method:    getInterface
 * Signature: (Ljava/lang/String;Losvr/clientkit/Interface;)J
 */
JNIEXPORT jlong JNICALL Java_osvr_clientkit_ContextWrapper_getInterface
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     osvr_clientkit_ContextWrapper
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_ContextWrapper_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
