/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_clientkit_OSVR_Viewer */

#ifndef _Included_osvr_clientkit_OSVR_Viewer
#define _Included_osvr_clientkit_OSVR_Viewer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_clientkit_OSVR_Viewer
 * Method:    getNumEyes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_osvr_clientkit_OSVR_1Viewer_getNumEyes
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Viewer
 * Method:    getEye
 * Signature: (ILosvr/clientkit/OSVR_Eye;)Losvr/clientkit/OSVR_Eye;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1Viewer_getEye
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Viewer
 * Method:    getSurface
 * Signature: (ILosvr/clientkit/OSVR_Surface;)Losvr/clientkit/OSVR_Surface;
 */
JNIEXPORT jobject JNICALL Java_osvr_clientkit_OSVR_1Viewer_getSurface
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Viewer
 * Method:    getViewerID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_osvr_clientkit_OSVR_1Viewer_getViewerID
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Viewer
 * Method:    getPose
 * Signature: (Losvr/util/OSVR_Pose3;)Z
 */
JNIEXPORT jboolean JNICALL Java_osvr_clientkit_OSVR_1Viewer_getPose
  (JNIEnv *, jobject, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Viewer
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1Viewer_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_clientkit_OSVR_Viewer
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_clientkit_OSVR_1Viewer_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
